### ISSUE TITLE
Build on macOS/Linux broken

### ISSUE THREAD

**Issue by stroborobo** [MicrosoftDocs/visualfsharpdocs#306]
Hey Team!

Do you think it'd be possible to get this to build on non-Windows systems?

I wanted to build a [Dash](https://kapeli.com/dash) docset for F#, but cannot build the HTML on my machine. I've modified the (downloaded) .openpublishing.buildcore.ps1 locally to use Mono's nuget and build paths using Join-Path instead of string literals, but I'm not done yet and don't know if there'll be a mayor barrier soon.

Or is there a HTML already for download somewhere? I mean self-contained of course.

**Comment by josselinauguste** [comment]
@stroborobo have you made any progress in your attempt to build a dash docset for this documentation? I was planning to do the same

**Comment by stroborobo** [comment]
No, I kinda dropped it tbh. But an easier way than getting it to build would have been to just replace the custom markdown directives for the snippets (`[!code-fsharp[Main](path/to/snippet)`) with their content, rewrite some links (because case sensitivity is hard apparently) and then it's good for indexing and rendering I guess. Styles would still be missing of course though. 

There's not going to be any updates to this repo anymore, so we'll just have to use what we have. The new repo doesn't contain the F# Core lib yet, or does it?

I still have this on my list, but I'm quite busy and easily distracted these days, so no promises :)

**Comment by mairaw** [comment]
Not sure if the instructions for building the .NET docs are still working, but you could give it a try:
https://github.com/dotnet/docs/blob/master/CONTRIBUTING.md#building-the-docs

**Comment by josselinauguste** [comment]
I can't build neither of the documentations :/

I'll start by trying to confirm with anyone involved in the documentation maintenance that the VisualFSharp documentation will actually migrate soon to the dotnet/docs repository, so I'll not have to do the job twice. To be continued...

**Comment by dend** [comment]
Hi folks,

We will be decommissioning the documentation in this repo once we fully migrate content to the dotnet/docs repo. We are currently in the process of doing so.

Den

**Comment by josselinauguste** [comment]
Great, so I'll wait for the documentation to be fully migrated :-)

**Comment by stroborobo** [comment]
@josselinauguste It's not finished yet, but here's where I am right now: https://github.com/foobarius1/fsharp-docset

After the recent HN thread about live coding via stream I thought I'd start streaming myself learning F#. This is both my first personal F# project and my first stream: https://www.twitch.tv/videos/237940722

**Comment by josselinauguste** [comment]
@stroborobo awesome idea! I'll have a look at it, ping me if you need some help 👍

**Comment by josselinauguste** [comment]
@dend Any news about the decommissioning of this documentation?

**Comment by mairaw** [comment]
I just sent an e-mail to the team asking about this today. @dendeli-msft can you comment?

**Comment by stroborobo** [comment]
Strangely none of the actual API docs from this repo seem to have been migrated. Or did I just not find it?
