### ISSUE TITLE
NOTE: frozen content

### ISSUE THREAD

**Issue by cartermp** [MicrosoftDocs/visualfsharpdocs#307]
Since docs.microsoft.com API reference content has been updated with preliminary F# signature support, all of this content which maps to MSDN is frozen. I don't have write access to this repo (must have been lost in the transfer from microsoft/visualfsharpdocs).

**Comment by mairaw** [comment]
Your access issue should have been solved now 😊

The PR for the F# signatures on .NET API docs hasn’t been merged yet, but it should be soon.

**Comment by cartermp** [comment]
Thanks @mairaw!
