### ISSUE TITLE
Missing documentation for List.allPairs

### ISSUE THREAD

**Issue by hickford** [MicrosoftDocs/visualfsharpdocs#310]
Hi. https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/collections.list-module-%5Bfsharp%5D is missing documentation for the [List.allPairs function](https://github.com/Microsoft/visualfsharp/pull/989) introduced 2016

Documentation for Array.allPairs and Seq.allPairs is also missing

**Comment by jkonecki** [comment]
Hey Microsoft, it's nearly a YEAR and you cannot provide documentation for methods in one of the most basic modules!

**Comment by hickford** [comment]
Link in original issue is dead, but I found List.allPairs documented at https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-listmodule.html#allPairs
