### ISSUE TITLE
eye-candy use FSharp.Formatting to process snippet files

### ISSUE THREAD

**Issue by smoothdeveloper** [MicrosoftDocs/visualfsharpdocs#71]
It would be awesome to have outstanding pretty printing done by @tpetricek FSharp.Formatting project on all F# snippets.

I think for newcommers to the language and with the type inference, this is going to be an important element to make the docs pretty.

Referencing #19 #58

**Comment by dsyme** [comment]
Content has been migrated, closing all old issues in this repo
