### ISSUE TITLE
F# Article on TechNet

### ISSUE THREAD

**Issue by dend** [MicrosoftDocs/visualfsharpdocs#82]
This takes the first hit on Bing and the second one on Google:
[Using Visual Studio to Write F# Programs](https://technet.microsoft.com/en-us/systemcenter/dd233169%28v=vs.90%29.aspx)

This should not be available and should redirect to [the main page in the new docs](https://msdn.microsoft.com/visualfsharpdocs/conceptual/using-visual-studio-to-write-fsharp-programs).

**Comment by smoothdeveloper** [comment]
Do we have this content (which might not be most up-to-date but still) in this repository?

**Comment by dend** [comment]
@smoothdeveloper Yep, the URL for the new file is the name of the `.md` representation in the repo.

**Comment by smoothdeveloper** [comment]
@dend sorry got it, I mistakenly took the link to the doc as "it should point to the homepage" :)

**Comment by dend** [comment]
@smoothdeveloper no, it's more something that we need to fix on our side to properly redirect to the new doc.
